name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache files
        uses: actions/cache@v4
        with:
            path: |
                ~/.sonar
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
      - name: Run Codescan On Push
        if: github.event_name == 'push'
        uses: codescan-io/codescan-scanner-action@1.4
        with:
          codeScanUrl: https://preview.codescan.io/
          organization: salil-june-24
          projectKey: papex-workflow
          login: ${{ secrets.codescan_token }}
          generateSarifFile: true
          failOnRedQualityGate: false
      - name: Run Codescan On PR
        if: github.event_name == 'pull_request'
        uses: codescan-io/codescan-scanner-action@1.4
        with:
          codeScanUrl: https://preview.codescan.io/
          organization: salil-june-24
          projectKey: papex-workflow
          login: ${{ secrets.codescan_token }}
          generateSarifFile: true
          failOnRedQualityGate: false
          scanChangedFilesOnly: true
          args: |
            sonar.pullrequest.branch=${{github.head_ref}}
            sonar.pullrequest.base=${{github.base_ref}}
            sonar.pullrequest.key=${{github.event.number}}
            sonar.inclusions=${{steps.changed-files.outputs.all_changed_and_modified_files}}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: codescan.sarif
